spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeus?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: fumartotp@gmail.com
    password: fumartotp123
    personal: Fumart.vn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
